#ifndef __LIBINSANE_GOBJECT_CAPABILITY_H
#define __LIBINSANE_GOBJECT_CAPABILITY_H

/**
 * LibinsaneCapability:
 * Not actually an enum but a bit field.
 */
typedef enum
{
	LIBINSANE_CAPABILITY_EMULATED,
	LIBINSANE_CAPABILITY_AUTOMATIC,
	LIBINSANE_CAPABILITY_HW_SELECT,
	LIBINSANE_CAPABILITY_SW_SELECT,
} LibinsaneCapability;

#endif
