#ifndef __LIBINSANE_GOBJECT_IMG_FORMAT_H
#define __LIBINSANE_GOBJECT_IMG_FORMAT_H

typedef enum
{
	LIBINSANE_IMG_FORMAT_RAW_RGB_24,

	LIBINSANE_IMG_FORMAT_GRAYSCALE_8,
	LIBINSANE_IMG_FORMAT_BW_1,
	LIBINSANE_IMG_FORMAT_BMP,
	LIBINSANE_IMG_FORMAT_GIF,
	LIBINSANE_IMG_FORMAT_JPEG,
	LIBINSANE_IMG_FORMAT_PNG,
} LibinsaneImgFormat;

#endif
