#ifndef __LIBINSANE_GOBJECT_UNIT_H
#define __LIBINSANE_GOBJECT_UNIT_H

typedef enum
{
	LIBINSANE_UNIT_NONE = 0,
	LIBINSANE_UNIT_PIXEL,
	LIBINSANE_UNIT_BIT,
	LIBINSANE_UNIT_MM,
	LIBINSANE_UNIT_DPI,
	LIBINSANE_UNIT_PERCENT,
	LIBINSANE_UNIT_MICROSECOND,
} LibinsaneUnit;

#endif
